/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hubBridgeSol from "./HubBridge.sol";
export type { hubBridgeSol };
import type * as hubBridgeL1Sol from "./HubBridgeL1.sol";
export type { hubBridgeL1Sol };
export type { MockInbox } from "./MockInbox";
export type { SpokeBridgeL1 } from "./SpokeBridgeL1";
export type { TestNFT } from "./TestNFT";
export type { WrappedNFT } from "./WrappedNFT";
