/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockEndpointV2Interface extends Interface {
  getFunction(
    nameOrSignature: "quote" | "send" | "setDelegate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "quote",
    values: [BigNumberish, AddressLike, BytesLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [BigNumberish, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelegate",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDelegate",
    data: BytesLike
  ): Result;
}

export interface MockEndpointV2 extends BaseContract {
  connect(runner?: ContractRunner | null): MockEndpointV2;
  waitForDeployment(): Promise<this>;

  interface: MockEndpointV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  quote: TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: AddressLike,
      arg2: BytesLike,
      arg3: BytesLike,
      arg4: boolean
    ],
    [[bigint, bigint] & { nativeFee: bigint; lzTokenFee: bigint }],
    "view"
  >;

  send: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike, arg2: BytesLike, arg3: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        guid: string;
        nonce: bigint;
        nativeFee: bigint;
        lzTokenFee: bigint;
      }
    ],
    "payable"
  >;

  setDelegate: TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "quote"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: AddressLike,
      arg2: BytesLike,
      arg3: BytesLike,
      arg4: boolean
    ],
    [[bigint, bigint] & { nativeFee: bigint; lzTokenFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "send"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike, arg2: BytesLike, arg3: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        guid: string;
        nonce: bigint;
        nativeFee: bigint;
        lzTokenFee: bigint;
      }
    ],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setDelegate"
  ): TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  filters: {};
}
