/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HubBridgeL1__factory } from "./HubBridgeL1__factory";
export { IInbox__factory } from "./IInbox__factory";
