/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMintableERC721,
  IMintableERC721Interface,
} from "../../../contracts/HubBridge.sol/IMintableERC721";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMintableERC721__factory {
  static readonly abi = _abi;
  static createInterface(): IMintableERC721Interface {
    return new Interface(_abi) as IMintableERC721Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMintableERC721 {
    return new Contract(address, _abi, runner) as unknown as IMintableERC721;
  }
}
