/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { MockInbox, MockInboxInterface } from "../../contracts/MockInbox";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "createRetryableTicket",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "nextTicketId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001b57600160005561011f90816100218239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c9081636031a52f1460d1575063679b6ded14603457600080fd5b61010036600319011260c6576001600160a01b036004358181160360cd576064358181160360cd576084359081160360c65760e43567ffffffffffffffff80821160c9573660238301121560c957816004013590811160c9573691016024011160c6578054600019811460b257602091600182019055604051908152f35b634e487b7160e01b82526011600452602482fd5b80fd5b8280fd5b5080fd5b90503460cd578160031936011260cd57602091548152f3fea264697066735822122075e092b89bfcc519fd3ff976c756849953798a6c676b89639c2dd79ecc97709664736f6c63430008140033";

type MockInboxConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockInboxConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockInbox__factory extends ContractFactory {
  constructor(...args: MockInboxConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockInbox & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockInbox__factory {
    return super.connect(runner) as MockInbox__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockInboxInterface {
    return new Interface(_abi) as MockInboxInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockInbox {
    return new Contract(address, _abi, runner) as unknown as MockInbox;
  }
}
