/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { MockInbox, MockInboxInterface } from "../../contracts/MockInbox";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "createRetryableTicket",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "nextTicketId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052600160005534801561001557600080fd5b5061036f806100256000396000f3fe6080604052600436106100295760003560e01c80636031a52f1461002e578063679b6ded14610059575b600080fd5b34801561003a57600080fd5b50610043610089565b60405161005091906100d8565b60405180910390f35b610073600480360381019061006e91906101ec565b61008f565b60405161008091906100d8565b60405180910390f35b60005481565b60008060005490506000808154809291906100a9906102f1565b9190505550809150509998505050505050505050565b6000819050919050565b6100d2816100bf565b82525050565b60006020820190506100ed60008301846100c9565b92915050565b600080fd5b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000610128826100fd565b9050919050565b6101388161011d565b811461014357600080fd5b50565b6000813590506101558161012f565b92915050565b610164816100bf565b811461016f57600080fd5b50565b6000813590506101818161015b565b92915050565b600080fd5b600080fd5b600080fd5b60008083601f8401126101ac576101ab610187565b5b8235905067ffffffffffffffff8111156101c9576101c861018c565b5b6020830191508360018202830111156101e5576101e4610191565b5b9250929050565b60008060008060008060008060006101008a8c03121561020f5761020e6100f3565b5b600061021d8c828d01610146565b995050602061022e8c828d01610172565b985050604061023f8c828d01610172565b97505060606102508c828d01610146565b96505060806102618c828d01610146565b95505060a06102728c828d01610172565b94505060c06102838c828d01610172565b93505060e08a013567ffffffffffffffff8111156102a4576102a36100f8565b5b6102b08c828d01610196565b92509250509295985092959850929598565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006102fc826100bf565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff820361032e5761032d6102c2565b5b60018201905091905056fea26469706673582212208515a5ce5b9526acb05678dd0e1ec273c338fe02955ebc6b980d8a3e28e8a6c964736f6c63430008140033";

type MockInboxConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockInboxConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockInbox__factory extends ContractFactory {
  constructor(...args: MockInboxConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockInbox & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockInbox__factory {
    return super.connect(runner) as MockInbox__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockInboxInterface {
    return new Interface(_abi) as MockInboxInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockInbox {
    return new Contract(address, _abi, runner) as unknown as MockInbox;
  }
}
